disabled_rules:
  - trailing_whitespace
  - line_length
  - force_cast
  - force_unwrapping

opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - empty_string
  - fallthrough
  - first_where
  - modifier_order
  - operator_usage_whitespace
  - overridden_super_call
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - single_test_class
  - sorted_first_last
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

excluded:
  - Pods
  - .build
  - Package.swift

line_length:
  warning: 150
  error: 200
  ignores_comments: true

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 60
  error: 100

identifier_name:
  min_length:
    warning: 2
  excluded:
    - id
    - x
    - y
    - z
